# This is a basic workflow to help you get started with Actions

name: SlackGit

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send Slack Message
        uses: parkingboss/slackbot-postmessage@v1
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          request: '{\"channel\":\"C032NCAKJPR\",\"text\":\"Hello world\"}'
      
